.TH "Crawlies" 1 "" "X Version 11"
.SH NAME
Crawlies \- crawling worms screen saver.
.SH SYNOPSIS
.B Crawlies
[\--root]
[\-c]
.SH DESCRIPTION
Crawlies is a screen saver for use with XScreenSaver that generates a
a host of crawling worms that worm their way across the screen.  Worm colors
are set by palettes that can be rotated by Crawlies.  Crawlies is part of
the IdleScreen project
(\fIhttp://sites.google.com/site/idlescreenproject\fP).
.SH OPTIONS
.TP 8
.B \--root
Draw on the root window.
.TP 8
.B \-c
Display the configuration dialog.
.SH "SEE ALSO"
.BR X (1),
.BR xscreensaver (1),
.BR xscreensaver-demo (1),
.BR PlasmaLenz (1),
.BR AcidRain (1)
.SH COPYRIGHT
Copyright \(co 2008 by Jeff Backus and the IdleScreen Project.

Crawlies is released under the GNU General Public License version 2.  It
is distributed AS IS, without any warranty WHAT SO EVER.  A copy of the
GPLv2 can be obtained from
\fIhttp://www.gnu.org/licenses/old-licenses/gpl-2.0.html\fP
.SH AUTHOR
Jeff Backus

