.TH "PlasmaLenz" 1 "" "X Version 11"
.SH NAME
PlasmaLenz \- plasma fractal screen saver.
.SH SYNOPSIS
.B PlasmaLenz
[\--root]
[\-c]
.SH DESCRIPTION
PlasmaLenz is a screen saver fo use with XScreenSaver that generates a
plasma fractal, then rotates through the palette, reminiscent of the demos
of days gone by.  PlasmaLenz is part of the IdleScreen project
(\fIhttp://idlescreen.googlepages.com\fP).
.SH OPTIONS
.TP 8
.B \--root
Draw on the root window.
.TP 8
.B \-c
Display the configuration dialog.
.SH "SEE ALSO"
.BR X (1),
.BR xscreensaver (1),
.BR xscreensaver-demo (1)
.SH COPYRIGHT
Copyright \(co 2008 by Jeff Backus and the IdleScreen Project.

PlasmaLenz is released under the GNU General Public License version 2.  It
is distributed AS IS, without any warranty WHAT SO EVER.  A copy of the
GPLv2 can be obtained from
\fIhttp://www.gnu.org/licenses/old-licenses/gpl-2.0.html\fP
.SH AUTHOR
Jeff Backus

